import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import SplashScreen from "./components/splashscreen";
import Footer from "./components/footer";



export const metadata: Metadata = {
  title: "Sioufi & Co",
  description: "Generated by qwerty",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <SplashScreen />
        <Navbar />
          {children}

        <Footer />
      </body>
    </html>
  );
}
